name: Build Application

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Check dotnet cli
        run: dotnet --version
      - name: Chec npm cli
        run: npm --version
