name: Build Application

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v2
        
      - name: Check dotnet cli
        run: dotnet --version
    
      - name: Build server
        run: dotnet build TrickingLibrary.sln
        
      - name: List after build TrickingLibrary.sln
        run: ls ./TrickingLibrary.WebApi -R

      - name: Chec npm cli
        run: npm --version
